### ISSUE TITLE
Dev server doesn't work

### ISSUE THREAD

**Issue by marr** [css-modules/webpack-demo#26]
I was hoping to get this up and running to quickly iterate on some css-module experiments. It seems the `npm start` task is broken. I see `webpack-dev-server` start but when I browse to localhost:8080 there is nothing served.

**Comment by lacrx** [comment]
I'm getting the exact same issue. I ran npm install, then npm start, and this is my error log.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart webpack-demo@1.0.0
6 info start webpack-demo@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info webpack-demo@1.0.0 Failed to exec start script
9 verbose stack Error: webpack-demo@1.0.0 start: `webpack-dev-server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid webpack-demo@1.0.0
11 verbose cwd /Users/thomas/repos/webpack-demo-master
12 error Darwin 15.6.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.6.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error webpack-demo@1.0.0 start: `webpack-dev-server`
17 error Exit status 1
18 error Failed at the webpack-demo@1.0.0 start script 'webpack-dev-server'.
18 error This is most likely a problem with the webpack-demo package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack-dev-server
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs webpack-demo
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls webpack-demo
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by shaozj** [comment]
me too

**Comment by marr** [comment]
Try changing the listen call to 127.0.0.1 instead of localhost. Better yet use create-react-app
